name: Test
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v1
      with:
        go-version: 1.23
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...
